### ISSUE TITLE
Panic when using `#[derive(Hash)]` for enum

### ISSUE THREAD

**Issue by marshtompsxd** [secure-foundations/verus#168]
I found that verus panicked when running against the following program:
```
xudongs@xudongs-a01:~/verus/source:$ cat rust_verify/example/myexample.rs                   
#[derive(Hash)]
pub enum StringL {
    Str1,
    Str2,
}

fn main() { }

xudongs@xudongs-a01:~/verus/source:$ ./tools/rust-verify.sh rust_verify/example/myexample.rs
thread 'rustc' panicked at 'no entry found for key', vir/src/well_formed.rs:25:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/xudongs/verus/source/rust_verify/src/driver.rs:80:40
```

If we remove Hash or replace it with Eq or other bounds, verus will not panic.

**Comment by utaal** [comment]
As @tjhance this is due to the derived function referencing `Hash`, which Verus currently doesn't support (in verified code).
Derives (other than `PartialEq`, `Eq`, and `Structural`) are also probably not generally supported.
@tjhance's PR should show a better error message when referencing external items.

Again, feel free to reopen if you have follow-ups.
