### ISSUE TITLE
Question about implementing a Map-like struct for exec mode

### ISSUE THREAD

**Issue by marshtompsxd** [secure-foundations/verus#169]
According to https://github.com/secure-foundations/verus/issues/167, I was trying to implement a Map-like struct for exec mode. I checked how vec is implemented and was trying to implement a dict as a wrapper around std::HashMap. However, when I define the dict struct with generics, it seems that I cannot specify bounds. More details below:
```
xudongs@xudongs-a01:~/verus/source:$ cat rust_verify/example/myexample.rs                   
#[verifier(external_body)]
pub struct Dict<#[verifier(maybe_negative)] K: std::cmp::Eq + std::hash::Hash, #[verifier(strictly_positive)] V> 
{
    pub dict: std::collections::HashMap<K, V>,
}

fn main() { }

xudongs@xudongs-a01:~/verus/source:$ ./tools/rust-verify.sh rust_verify/example/myexample.rs
error: not yet supported: bounds on datatype parameters
  --> rust_verify/example/myexample.rs:21:1
   |
21 | / pub struct Dict<#[verifier(maybe_negative)] K: std::cmp::Eq + std::hash::Hash, #[verifier(strictly_pos...
22 | | {
23 | |     pub dict: std::collections::HashMap<K, V>,
24 | | }
   | |_^

error: aborting due to previous error
```
I have also tried to use `where` clause to specify bounds but `where` is not supported as well. 

Could you please let me know what is the best way for me to specify bounds since it is necessary to implement a wrapper around HashMap? If this can work I am happy to implement a dict for exec mode and send a PR if it is needed.

**Comment by tjhance** [comment]
Verus support for traits is pretty limited, but it _is_ possible to add trait bounds on impls and functions:

```
#[verifier(external_body)]
pub struct Dict<#[verifier(maybe_negative)] K, #[verifier(strictly_positive)] V>
{
    pub dict: std::collections::HashMap<K, V>,
}

impl<K: std::cmp::Eq + std::hash::Hash, V> Dict<K, V> {
    #[verifier(external_body)]
    fn new() -> Self {
        Dict { dict: HashMap::new() }
    }
}
```

Unfortunately, there are going to be some more limitations.

  * For one, Verus currently doesn't handle externally-defined traits, so you won't be able to implement `Hash` or `Eq` on any datatype you define
  * Verus doesn't yet support trait bounds on types that aren't structs.

However, if you're willing to abide by the second point, you can get around the first point by creating your own `Hash` trait. In fact, I think you'll want to do this _anyway_, because the trait needs some extra specifications on it. I'm assuming you want to give your `Dict` type a specification that it acts like a Verus `Map`, in which case you need conditions like:
 * The hash function is deterministic
 * The equality function matches the equality at the SMT level (since this is how `Map` distinguishes keys)

I believe this should suffice:

```rust
pub trait HashEq {
  #[spec]
  fn hash(&self) -> u64 {
      no_method_body()
  }

  #[exec]
  fn compute_hash(&self) -> u64 {
      // Result matches a deterministic function
      ensures(|res: u64| res == self.hash());
      no_method_body()
  }

  #[exec]
  fn compute_eq(&self, other: &Self) -> bool {
      // equality matches the SMT equality of the objects
      ensures(|res: bool| res == equal(self, other));
      no_method_body()
  }
}
```

Then clients can implement `HashEq` to prove that the hash function matches the desired properties. You could then implement Hash and Eq in terms of HashEq (using `external_body`) though in principle you could implement the hash table from scratch and verify it.

**Comment by marshtompsxd** [comment]
@tjhance Thank you a lot for the guide! I will try what you suggested

**Comment by marshtompsxd** [comment]
Hi @tjhance Thank you for your help again. I was trying to implement the Hash trait for my struct `StringL`. The signature of the `hash` function is
```
fn hash<H: Hasher>(&self, state: &mut H)
```
so I was trying to do sth like
```
impl std::hash::Hash for StringL {
    #[verifier(external_body)]
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        // do something
    }
}
```
However, verus reports error like
```
error: not yet supported: bounds on method type parameters
  --> rust_verify/example/myexample.rs:81:5
   |
81 |     fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```
Could you please let me know is there a way to specify bounds on method type parameters that verus supports?

**Comment by tjhance** [comment]
You should be able to do this now:

```rust
#[verifier(external)]
impl std::hash::Hash for StringL {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        // do something
    }
}
```

(note: it's `external`, not `external_body`)

**Comment by marshtompsxd** [comment]
@tjhance Thank you! `external` works

**Comment by utaal** [comment]
I'm going to close this, but feel free to reopen if you have follow up questions.
