### ISSUE TITLE
Instability in `state_machines/dist_rwlock.rs`

### ISSUE THREAD

**Issue by utaal** [secure-foundations/verus#218]
Example `state_machines/dist_rwlock.rs` is currently ignored because it fails with z3 4.10.1

**Comment by tjhance** [comment]
I'm re-opening this because it flakes again so I added the 'ignore' line again.

For posterity, the flaky code can be found here: https://github.com/secure-foundations/verus/blob/5e0c05eac90283880575e18360c5fdd65dd31acb/source/rust_verify/example/state_machines/dist_rwlock.rs

Earlier, @Chris-Hawblitzel pointed out that:

> This looks like a Z3 issue to me.  It's unstable and the problem goes away if the function gets its own Z3 query.  And it doesn't look like some subtle incompleteness due to unpredictable triggering or nonlinear arithmetic or timeouts or anything -- it really is failing immediately on assume foo; assert foo; where foo is a perfectly reasonable expression.

(Though, it turned out that even with its own Z3 query, the proof was still unstable.)

We should probably attempt to fix the underlying issue here, either follow up with Z3 and/or add extra smarts to Verus to work around this kind of thing.

**Comment by tjhance** [comment]
OK, this is actually fixed again (6fa380e24d8f4cfd1adc41d7578e2ca695b51eb7) thanks to @utaal adding more triggers. I'm going to close again and add a new issue for the underlying issue.
