### ISSUE TITLE
`recommends_by` is unsound

### ISSUE THREAD

**Issue by utaal** [secure-foundations/verus#228]
This passes the recommends check for `s.index(x)` which recommends `x < s.len()`:

```rust
spec(checked) fn lol(s: Seq<nat>) -> nat
{
    recommends_by(check_lol);
    s.index(0)
}

#[verifier(recommends_by)]
proof fn check_lol(s: Seq<nat>)
{
    assert(false);
}
```

This is because we treat `assert` (and proof functions in general) as any other function for which we're checking recommends and we just assume its postcondition to be true, which lets us assume false.

cc @Chris-Hawblitzel 

`assert` is defined as:
```rust
#[proof]
#[verifier(custom_req_err("assertion failure"))]
pub fn assert(b: bool) {
    requires(b);
    ensures(b);
}
```

Initially reported by @matthias-brun.

**Comment by utaal** [comment]
* [ ] It may also be incomplete. In one case an assignment was completely missing from the encoding.

**Comment by Chris-Hawblitzel** [comment]
One thing to keep in mind is that "recommends" checking is a bug finding tool for helping to find some bugs in trusted specifications or helping to diagnose real verification errors.  It's not designed to perform sound verification like the regular checking is.  For example, you can always write `recommends false` and no one is obligated to satisfy this recommendation.

That said, I totally agree that we ought to check the regular calls to proof functions in `recommends_by` proofs, because that's the point of writing the calls to the proof functions in the first place.  Commit e035639e338dd5481b618f84c4c358eeca6d33e7 should fix this.

**Comment by utaal** [comment]
> One thing to keep in mind is that "recommends" checking is a bug finding tool for helping to find some bugs in trusted specifications or helping to diagnose real verification errors. It's not designed to perform sound verification like the regular checking is. For example, you can always write `recommends false` and no one is obligated to satisfy this recommendation.

Yea, I wasn't sure whether to even tag this as a `soundness` issue. As you say, it's only a soundness issue _in the context of_ recommends checks, which has a different goal than sound verification.

**Comment by utaal** [comment]
Fixed by https://github.com/secure-foundations/verus/commit/e035639e338dd5481b618f84c4c358eeca6d33e7
