### ISSUE TITLE
introduction of temp variable causes flakiness

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/verus#86]
Below, `dec_to_zero_asserts` and `dec_to_zero_asserts2` are almost the same, except that one uses a tmp variable assignment. However, only one of them passes. (Interestingly, the line that passes or fail is earlier than the changed line, but since it's all one query, this isn't _too_ surprising.)

(This is macro-generated code, by the way, if you're wondering why it looks a little weird - the reason this came up is that I was trying to introduce temp variables in the generated code.)

```rust
#[allow(unused_imports)]
use builtin::*;
mod pervasive;
use pervasive::*;
use pervasive::modes::*;
use pervasive::option::*;

pub struct RefCounter<#[verifier(maybe_negative)] T> {
    pub counter: nat,
    pub storage: crate::pervasive::option::Option<T>,
    pub reader: crate::pervasive::multiset::Multiset<T>,
}

impl<#[verifier(maybe_negative)] T> RefCounter<T> {
    #[spec]
    pub fn invariant(&self) -> ::std::primitive::bool {
        self.reader_agrees_storage()
            && self.counter_agrees_storage()
            && self.counter_agrees_storage_rev()
            && self.counter_agrees_reader_count()
    }
    #[spec]
    fn reader_agrees_storage(&self) -> bool {
        forall(|t: T| self.reader.count(t) > 0 >>= equal(self.storage, Option::Some(t)))
    }
    #[spec]
    fn counter_agrees_storage(&self) -> bool {
        self.counter == 0 >>= self.storage.is_None()
    }
    #[spec]
    fn counter_agrees_storage_rev(&self) -> bool {
        self.storage.is_None() >>= self.counter == 0
    }
    #[spec]
    fn counter_agrees_reader_count(&self) -> bool {
        self.storage.is_Some() >>= self.reader.count(self.storage.get_Some_0()) == self.counter
    }

    #[proof]
    pub fn dec_to_zero_asserts(self: RefCounter<T>, x: T) {
        crate::pervasive::assume(self.invariant());
        {
            crate::pervasive::assume((self.reader).count(x) >= 1);
            crate::pervasive::assume(self.counter < 2);
            crate::pervasive::assert(self.counter == 1); // THIS FAILS

            let update_tmp_0 = x;
            crate::pervasive::assert(::builtin::equal(
                self.storage,
                crate::pervasive::option::Option::Some(update_tmp_0),
            ));
        }
    }

    #[proof]
    pub fn dec_to_zero_asserts2(self: RefCounter<T>, x: T) {
        crate::pervasive::assume(self.invariant());
        crate::pervasive::assume((self.reader).count(x) >= 1);
        crate::pervasive::assume(self.counter < 2);
        crate::pervasive::assert(self.counter == 1); // THIS PASSES
        crate::pervasive::assert(::builtin::equal(
            self.storage,
            crate::pervasive::option::Option::Some(x),
        ));
    }
}

fn main() { }
```

**Comment by Chris-Hawblitzel** [comment]
There are two issues here.  The first has to do with Z3 unpredictability and the second with trigger selection.

First, in this example, `Option::Some(t)` was the trigger for the `forall` quantifier, so that an occurrence of `Option::Some(...)` needed to appear before the assertion that `self.counter == 1`.  Otherwise, this assertion isn't provable given the facts available at that point in the code.  However, Z3 is always free to instantiate quantifiers for any reason, including occurrences of `Option::Some(...)` _after_ the assertion we're trying to prove.  These "extra" quantifier instantiations are unpredictable.  Any proof that accidentally relies on them may be flaky.  I don't know of a way to fix this unpredictability without changing Z3 substantially.

Second, the trigger `Option::Some(t)` is not a good trigger.  The other trigger candidate, `self.reader.count(t)`, would probably be better.  I tweaked the automatic trigger selection algorithm slightly ( ca79df96a745592663c7769c68c1bf81d3a650f5 ) so that Verus now chooses the better trigger in this case.  But in general, Verus cannot always predict what the best trigger will be.  It could choose all the trigger candidates (in this case, both `Option::Some(t)` and `self.reader.count(t)`), but it deliberately avoids doing this because having unnecessary extra triggers like `Option::Some(t)` leads to too many quantifier instantiations and slow verification.  So instead, I just pushed a commit ( ae45da88f92034dc00619df92b6d12cac5213d58 ) that prints a note whenever Verus has doubts about its automatic choice of triggers.  The note encourages the programmer to consider whether Verus chose an appropriate trigger and to provide confirmation via an `#[auto_trigger]` annotation or to manually override the choice via `#[trigger]` annotations:

```
Verifying root module

note: automatically chose triggers for this expression:
  --> .\rust_verify\example\features.rs:32:9
   |
32 |         forall(|t: T| self.reader.count(t) > 0 >>= equal(self.storage, Option::Some(t)))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note:   trigger 1 of 1:
  --> .\rust_verify\example\features.rs:32:23
   |
32 |         forall(|t: T| self.reader.count(t) > 0 >>= equal(self.storage, Option::Some(t)))
   |                       ^^^^^^^^^^^^^^^^^^^^

note: Verus printed one or more automatically chosen quantifier triggers
      because it had low confidence in the chosen triggers.
      To suppress these messages, do one of the following:
        (1) manually annotate a single desired trigger using #[trigger]
            (example: forall(|i: int, j: int| f(i) && #[trigger] g(i) && #[trigger] h(j))),
        (2) manually annotate multiple desired triggers using with_triggers
            (example: forall(|i: int| with_triggers!([f(i)], [g(i)] => f(i) && g(i)))),
        (3) accept the automatically chosen trigger using #[auto_trigger]
            (example: forall(|i: int, j: int| #[auto_triggers] f(i) && g(i) && h(j)))
        (4) use the --triggers-silent command-line option to suppress all printing of triggers.
      (Note: triggers are used by the underlying SMT theorem prover to instantiate quantifiers;
      the theorem prover instantiates a quantifier whenever some expression matches the
      pattern specified by one of the quantifier's triggers.)
  --> .\rust_verify\example\features.rs:32:9
   |
32 |         forall(|t: T| self.reader.count(t) > 0 >>= equal(self.storage, Option::Some(t)))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Verification results:: verified: 3 errors: 0
```

Verus does not print this message for all quantifiers, just those that it has low confidence in the automatic trigger selection.

**Comment by parno** [comment]
I like the idea of warning the user when Verus' confidence is low, and the suggested options should be very helpful!
